# Generated by Django 3.2.8 on 2021-10-14 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='country',
        ),
        migrations.AddField(
            model_name='news',
            name='content',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
