# Generated by Django 3.2.8 on 2021-12-03 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_app', '0002_auto_20211014_1014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
